server:
  port: 8080

spring:
  application:
    name: baseline-service-sgn

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
    healthcheck:
      enable: false 
      